export const COUNTIES = [
  "California",
  "Alameda County",
  "Contra Costa County",
  "Fresno County",
  "Humboldt County",
  "Marin County",
  "Monterey County",
  "Orange County",
  "San Bernardino County",
  "San Francisco County",
  "San Joaquin County",
  "San Luis Obispo County",
  "Santa Clara County",
  "Tulare County",
  "Tuolumne County",
  "Ventura County",
  "Chicago",
];
