"""adding sequencing_date to pathogenGenome

Create Date: 2021-06-15 15:50:28.220371

"""
import enumtables  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20210615_155026"
down_revision = "20210602_224122"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pathogen_genomes",
        sa.Column("sequencing_date", sa.Date(), nullable=True),
        schema="aspen",
    )
    op.alter_column(
        "pathogen_genomes",
        "num_unambiguous_sites",
        existing_type=sa.INTEGER(),
        comment="Number of sites with allele A, C, T, U or G",
        existing_comment="Number of sites with allele A, C, T, or G",
        existing_nullable=False,
        schema="aspen",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pathogen_genomes",
        "num_unambiguous_sites",
        existing_type=sa.INTEGER(),
        comment="Number of sites with allele A, C, T, or G",
        existing_comment="Number of sites with allele A, C, T, U or G",
        existing_nullable=False,
        schema="aspen",
    )
    op.drop_column("pathogen_genomes", "sequencing_date", schema="aspen")
    # ### end Alembic commands ###
