"""add uploaded_by to samples

Create Date: 2021-05-24 22:39:40.542732

"""
import enumtables  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20210524_223939"
down_revision = "20210510_090332"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "samples",
        sa.Column("uploaded_by_id", sa.Integer(), nullable=True),
        schema="aspen",
    )
    op.create_foreign_key(
        op.f("fk_samples_uploaded_by_id_users"),
        "samples",
        "users",
        ["uploaded_by_id"],
        ["id"],
        source_schema="aspen",
        referent_schema="aspen",
    )

    conn = op.get_bind()
    create_aspen_admin_sql = sa.sql.text(
        "INSERT INTO aspen.users(name, email, auth0_user_id, group_admin, system_admin, agreed_to_tos, group_id)"
        "VALUES('ASPIN ADMIN', 'fake@chanzuckerberg.com', )"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_samples_uploaded_by_id_users"),
        "samples",
        schema="aspen",
        type_="foreignkey",
    )
    op.drop_column("samples", "uploaded_by_id", schema="aspen")
    # ### end Alembic commands ###
