"""synchronize alembic

Create Date: 2022-09-07 22:08:45.648271

"""
import enumtables  # noqa: F401
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20220907_220840"
down_revision = "20220902_001655"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pathogen_genomes",
        "num_unambiguous_sites",
        existing_type=sa.INTEGER(),
        comment="Number of sites with allele A, C, T, U or G",
        existing_comment="Number of sites with allele A, C, T, or G",
        existing_nullable=False,
        schema="aspen",
    )
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="role name",
        existing_nullable=False,
        schema="aspen",
    )
    op.alter_column(
        "samples",
        "czb_failed_genome_recovery",
        existing_type=sa.BOOLEAN(),
        comment="This is set to true iff this sample was sequenced by CZB and failed genome recovery.",
        existing_comment="This is set to true iff this is sample sequenced by CZB and failed genome recovery.",
        existing_nullable=True,
        existing_server_default=sa.text("true"),
        schema="aspen",
    )
    # ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("don't downgrade")
