inputs:
  - name: "gisaid"
    metadata: "data/metadata_gisaid.tsv"
    sequences: "data/sequences_gisaid.fasta"
  - name: "aspen"
    metadata: "data/metadata_aspen.tsv"
    sequences: "data/sequences_aspen.fasta"
  - name: "selected"
    metadata: "data/metadata_selected.tsv"
    sequences: "data/sequences_selected.fasta"

builds:
  aspen:
    country: USA
    division: {division}
    location: {location}
    region: North America
    subsampling_scheme: group_only
    title: '{location}, {division}'

## custom rules
custom_rules:
  - nextstrain_profiles/nextstrain-gisaid/subsampling_ranges.smk

## Auxiliary files
files:
  lat_longs: "my_profiles/aspen/lat_longs.tsv"
  ordering: "my_profiles/aspen/ordering.tsv"
  description: "my_profiles/aspen/covidtrackerca.md"
  auspice_config: "my_profiles/aspen/aspen_auspice_config_v2.json"

## Parameters
refine:
  keep_polytomies: True

## Subsampling schemas
subsampling:
  group_only:
    focal:
      exclude: "--exclude-where 'selected!=yes'"
    same_county:
      group_by: "year month"
      max_sequences: 2000
      query: --query "(location == '{{location}}') & (division == '{{division}}')"
      priorities:
        type: "proximity"
        focus: "focal"
