#FROM ubuntu:20.04
FROM nextstrain/base
ARG DEBIAN_FRONTEND=noninteractive

LABEL maintainer = "Aspen"
LABEL description = "Image for Aspen ingest-gisaid workflow"

RUN sed -i s/archive.ubuntu.com/us-west-2.ec2.archive.ubuntu.com/ /etc/apt/sources.list; \
    echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/98idseq; \
    echo 'APT::Install-Suggests "false";' > /etc/apt/apt.conf.d/99idseq

RUN apt-get -qq update && apt-get -qq -y install \
    git \
    jq \
    moreutils \
    curl \
    locales \
    zip \
    unzip \
    httpie \
    zlib1g-dev \
    libhts-dev \
    pkg-config \
    apt-utils \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-yaml \
    python3-dateutil \
    python3-biopython \
    python3-regex \
    python3-dev \
    virtualenv \
    awscli \
    xz-utils \
    zstd \
    snakemake \
    mafft \
    wget \
    make \
    gcc \
    && locale-gen en_US.UTF-8
RUN pip3 install --no-cache-dir awscli pipenv

ENV FLASK_ENV=development
ENV PIPENV_PYTHON=/usr/src/app/

RUN pip3 install nextstrain-cli csv-diff s3fs[boto3] aiobotocore[awscli,boto3] envdir fsspec pandas

RUN mkdir /ncov && \
    cd /ncov && \
    git init && \
    git remote add origin https://github.com/nextstrain/ncov.git && \
    git fetch origin 3e9ad400593b24cf94d24cdb56366f339f5a165b && \
    git reset --hard FETCH_HEAD

WORKDIR /usr/src/app
COPY requirements.txt .
COPY Pipfile* ./
COPY third-party ./third-party/
COPY setup.py .
RUN pipenv install --dev --system --verbose && pipenv --clear

COPY . .
RUN pip3 install . third-party/sqlalchemy-enum-tables
