FROM python:3.10-slim AS base
ENV FLASK_APP=aspen.main
EXPOSE 3000

# Install poetry
RUN apt update && apt install -y libdigest-sha-perl wget
ENV POETRY_VERSION=1.3.2
RUN python3 -m pip install poetry==$POETRY_VERSION
# install libffi-dev (needed for installing cffi with python 3.10-slim image)
RUN apt-get --yes install libffi-dev

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y make wget git jq gcc unzip

# Install DB certs.
ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /usr/local/share/ca-certificates/global-bundle.crt
RUN update-ca-certificates

# install nextclade, check it installed correctly
RUN apt-get --yes install curl
RUN cd /usr/local/bin && curl -fsSL "https://github.com/nextstrain/nextclade/releases/download/2.14.0/nextclade-x86_64-unknown-linux-gnu" -o "nextclade" && chmod +x nextclade
RUN nextclade --version

# Poetry: install app
COPY pyproject.toml poetry.lock environment.yaml ./
COPY third-party ./third-party
RUN wget https://github.com/chanzuckerberg/oso/archive/czge-oso25.zip -O oso.zip && \
    unzip -q oso.zip && \
    mv oso-czge-oso25/languages/python/sqlalchemy-oso sqlalchemy-oso && rm oso.zip
RUN poetry config virtualenvs.create false && \
    poetry install
ENV PYTHONPATH=.
# FIXME Should figure out how to fold biopython install into poetry, but poetry
# breaks right now trying to add it to deps.
RUN pip install biopython

COPY . .
# Install the aspen package
RUN poetry install
