FROM nextstrain/base@sha256:9d65e6d5dee02fc59c57e0a5043af082ccf42c728aa0dfa867f7585a816a67c2
ARG DEBIAN_FRONTEND=noninteractive

LABEL maintainer = "CZ Gen Epi"
LABEL description = "Image for CZ Gen Epi ingest-gisaid workflow"

RUN sed -i s/archive.ubuntu.com/us-west-2.ec2.archive.ubuntu.com/ /etc/apt/sources.list; \
    echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/98idseq; \
    echo 'APT::Install-Suggests "false";' > /etc/apt/apt.conf.d/99idseq

RUN apt-get -qq update && apt-get -qq -y install \
    git \
    jq \
    moreutils \
    curl \
    locales \
    zip \
    unzip \
    httpie \
    zlib1g-dev \
    libhts-dev \
    pkg-config \
    apt-utils \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-yaml \
    python3-dateutil \
    python3-biopython \
    python3-regex \
    python3-dev \
    virtualenv \
    awscli \
    xz-utils \
    zstd \
    snakemake \
    mafft \
    wget \
    make \
    gcc \
    && locale-gen en_US.UTF-8

ENV FLASK_ENV=development

# Install poetry
ENV POETRY_HOME /opt/poetry/
RUN apt install -y libdigest-sha-perl
RUN wget https://raw.githubusercontent.com/python-poetry/poetry/1.1.10/get-poetry.py && \
    echo "e973b3badb95a916bfe250c22eeb7253130fd87312afa326eb02b8bdcea8f4a7  get-poetry.py" > get-poetry.py.sha256 && \
    shasum -a 256 -c get-poetry.py.sha256 && \
    python get-poetry.py && \
    rm get-poetry*

RUN pip3 install nextstrain-cli csv-diff s3fs[boto3] aiobotocore[awscli,boto3] envdir fsspec pandas arrow

RUN mkdir /ncov && \
    cd /ncov && \
    git init && \
    git remote add origin https://github.com/chanzuckerberg/ncov.git && \
    git fetch origin czgenepi && \
    git reset --hard FETCH_HEAD

# Poetry: install app
WORKDIR /usr/src/app
COPY pyproject.toml poetry.lock environment.yaml ./
COPY third-party ./third-party
RUN /opt/poetry/bin/poetry config virtualenvs.create false && \
    /opt/poetry/bin/poetry install
ENV PYTHONPATH=.

COPY . .
# Install the aspen package
RUN /opt/poetry/bin/poetry install

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT="unknown"
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}
