FROM nextstrain/base:build-20221207T221900Z
ARG DEBIAN_FRONTEND=noninteractive

LABEL maintainer = "CZ Gen Epi"
LABEL description = "Image for CZ Gen Epi ingest-gisaid workflow"

# TODO -- Preferably want to drop to non-root user for job runs.
# RUN commands below necessitate root for some of them. Nextstrain now has
# a non-root user (`USER nextstrain:nextstrain) as part of its Dockerfile
# https://github.com/nextstrain/docker-base/blob/master/Dockerfile#L259
# Probably want to use that once we have chance to test its fine for job runs.
USER root

RUN sed -i s/archive.ubuntu.com/us-west-2.ec2.archive.ubuntu.com/ /etc/apt/sources.list; \
    echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/98idseq; \
    echo 'APT::Install-Suggests "false";' > /etc/apt/apt.conf.d/99idseq

RUN apt-get -qq update && apt-get -qq -y install \
    git \
    jq \
    moreutils \
    curl \
    locales \
    zip \
    unzip \
    httpie \
    zlib1g-dev \
    libhts-dev \
    pkg-config \
    apt-utils \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-yaml \
    python3-dateutil \
    python3-biopython \
    python3-regex \
    python3-dev \
    virtualenv \
    awscli \
    xz-utils \
    zstd \
    snakemake \
    mafft \
    wget \
    make \
    gcc \
    && locale-gen en_US.UTF-8

ENV FLASK_ENV=development

# Install DB certs.
ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /usr/local/share/ca-certificates/global-bundle.crt
RUN update-ca-certificates

# Install poetry
RUN apt install -y libdigest-sha-perl
ENV POETRY_VERSION=1.3.2
RUN python3 -m pip install poetry==$POETRY_VERSION

RUN pip3 install nextstrain-cli csv-diff s3fs[boto3] aiobotocore[awscli,boto3] envdir fsspec pandas arrow
RUN pip3 uninstall -y pangoLEARN

RUN mkdir /ncov && \
    cd /ncov && \
    git init && \
    git remote add origin https://github.com/chanzuckerberg/ncov.git && \
    git fetch origin czgenepi && \
    git reset --hard FETCH_HEAD

# Poetry: install app
WORKDIR /usr/src/app
COPY pyproject.toml poetry.lock environment.yaml ./
COPY third-party ./third-party
RUN wget https://github.com/chanzuckerberg/oso/archive/czge-oso25.zip -O oso.zip && \
    unzip -q oso.zip && \
    mv oso-czge-oso25/languages/python/sqlalchemy-oso sqlalchemy-oso && rm oso.zip
RUN poetry config virtualenvs.create false && \
    poetry install
ENV PYTHONPATH=.

COPY . .
# Install the aspen package
RUN poetry install

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT="unknown"
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}
# TODO - Mismatch between poetry and augur deps forces us to manually install jsonschema v3 here
RUN pip install jsonschema==3.*

WORKDIR /nextstrain
