export enum ROUTES {
  HOMEPAGE = "/",
  DATA = "/data",
  TERMS = "/terms",
  PRIVACY = "/privacy",
  RESOURCES = "/resources",
  CONTACT_US_EMAIL = "mailto:helloaspen@chanzuckerberg.com",
  AGREE_TERMS = "/agreeTerms",
  FAQ = "/faq",
  DATA_SAMPLES = "/data/samples",
  PHYLO_TREES = "/data/phylogenetic_trees",
  UPLOAD = "/upload",
  UPLOAD_STEP1 = "/upload/1",
  UPLOAD_STEP2 = "/upload/2",
  UPLOAD_STEP3 = "/upload/3",
}
