export enum ROUTES {
  HOMEPAGE = "/",
  BIOHUB = "https://www.czbiohub.org/",
  CAREERS = "https://chanzuckerberg.com/careers/career-opportunities/?initiative=science",
  CZI = "https://chanzuckerberg.com/",
  DATA = "/data",
  GITHUB = "https://github.com/chanzuckerberg/aspen/",
  LANDINGV2 = "/landingv2",
  NEXTSTRAIN = "https://nextstrain.org/",
  TERMS = "/terms",
  PANGOLIN = "https://pangolin.cog-uk.io/",
  PRIVACY = "/privacy",
  CONTACT_US_EMAIL = "mailto:helloaspen@chanzuckerberg.com",
  AGREE_TERMS = "/agreeTerms",
  FAQ = "/faq",
  DATA_SAMPLES = "/data/samples",
  PHYLO_TREES = "/data/phylogenetic_trees",
  RESOURCES = "/resources",
  UPLOAD = "/upload",
  UPLOAD_STEP1 = "/upload/1",
  UPLOAD_STEP2 = "/upload/2",
  UPLOAD_STEP3 = "/upload/3",
  USHER = "https://genome.ucsc.edu/cgi-bin/hgPhyloPlace",
}
