export enum ENTITIES {
  SAMPLE_INFO = "SAMPLE_INFO",
  PHYLO_RUN_INFO = "PHYLO_RUN_INFO",
  USER_INFO = "USER_INFO",
  LOCATION_INFO = "LOCATION_INFO",
  LINEAGES_INFO = "LINEAGES_INFO",
  GROUP_INFO = "GROUP_INFO",
  GROUP_MEMBER_INFO = "GROUP_MEMBER_INFO",
}
