export const PRIVATE_ID_HEADER: Header = {
  key: "privateId",
  sortKey: ["privateId"],
  text: "Private ID",
  tooltip: {
    boldText: "Private ID",
    regularText:
      "User-provided private ID. Only users in your Group can see it.",
  },
};

export const PUBLIC_ID_HEADER: Header = {
  key: "publicId",
  sortKey: ["publicId"],
  text: "Public ID",
  tooltip: {
    boldText: "Public ID",
    regularText: "This is your GISAID ID or public ID generated by CZ Gen Epi.",
  },
};

export const COLLECTION_DATE_HEADER: Header = {
  key: "collectionDate",
  sortKey: ["collectionDate"],
  text: "Collection Date",
  tooltip: {
    boldText: "Collection Date",
    regularText:
      "User-provided date on which the sample was collected from an individual or an environment.",
  },
};

export const LINEAGE_HEADER: Header = {
  key: "lineage",
  sortKey: ["lineage", "lineage"],
  subHeaders: [
    {
      key: "lineage",
      text: "Lineage",
    },
    {
      key: "qc_status",
      text: "QC Status",
    },
    {
      key: "scorpio_call",
      text: "Scorpio Call",
    },
    {
      key: "scorpio_support",
      text: "Scorpio Support",
    },
    {
      key: "last_updated",
      text: "Last Updated",
    },
    {
      key: "version",
      text: "Version",
    },
  ],
  text: "Lineage",
  tooltip: {
    boldText: "Lineage",
    link: {
      href: "https://cov-lineages.org/pangolin.html",
      linkText: "Learn more.",
    },
    regularText:
      "A lineage is a named group of related sequences. A few lineages have been associated with changes in the epidemiological or biological characteristics of the virus. We continually update these lineages based on the evolving Pangolin designations. Lineages determined by Pangolin.",
  },
};

export const UPLOAD_DATE_HEADER: Header = {
  key: "uploadDate",
  sortKey: ["uploadDate"],
  text: "Upload Date",
  tooltip: {
    boldText: "Upload Date",
    regularText: "Date on which the sample was uploaded to CZ Gen Epi.",
  },
};

export const COLLECTION_LOCATION_HEADER: Header = {
  key: "collectionLocation",
  sortKey: ["collectionLocation"],
  subHeaders: [
    {
      key: "region",
      text: "Region",
    },
    {
      key: "country",
      text: "Country",
    },
    {
      key: "division",
      text: "Division",
    },
    {
      key: "location",
      text: "Location",
    },
  ],
  text: "Collection Location",
  tooltip: {
    boldText: "Collection Location",
    regularText:
      "User-provided geographic location where the sample was collected (at the county level or above).",
  },
};

export const SEQUENCING_DATE_HEADER = {
  key: "sequencingDate",
  sortKey: ["sequencingDate"],
  text: "Sequencing Date",
  tooltip: {
    boldText: "Sequencing Date",
    regularText: "User-provided date on which the sample was sequenced.",
  },
};

export const GISAID_HEADER = {
  key: "gisaid",
  sortKey: ["gisaid", "status"],
  subHeaders: [
    {
      key: "status",
      text: "GISAID Status",
    },
    {
      key: "gisaid_id",
      text: "GISAID ID",
    },
  ],
  text: "GISAID",
  tooltip: {
    boldText: "GISAID Status",
    regularText:
      "Whether your sample has been Not Yet Submitted, Submitted, Accepted (with GISAID accession), Rejected, or Not Eligible (marked private).",
  },
};
