import React, { useState } from "react";
import {
  StyledInfoOutlinedIcon,
  StyledTooltip,
} from "src/common/components/library/data_subview/components/CreateNSTreeModal/style";
import dataTableStyle from "src/common/components/library/data_table/index.module.scss";
import { TREE_STATUS } from "src/common/constants/types";
import TreeIcon from "src/common/icons/PhyloTree.svg";
import NextstrainConfirmationModal from "../NextstrainConfirmationModal";
import { PhyloTreeStatusTag } from "./components/PhyloTreeStatusTag";
import {
  CellWrapper,
  StyledNameWrapper,
  StyledRowContent,
  StyledTreeCreator,
} from "./style";

interface Props {
  value: string;
  item: Tree;
}

const TreeTableNameCell = ({ value, item }: Props): JSX.Element => {
  const [open, setOpen] = useState(false);
  const status = item?.status;
  const isDisabled = status !== TREE_STATUS.Completed;

  const handleClickOpen = () => {
    if (!isDisabled) setOpen(true);
  };

  const handleClose = () => {
    setOpen(false);
  };

  // TODO: Create a pathway to handle Trees with no id, for trees
  // that are in progress or failed
  const treeId = item.id as number;

  const { user } = item;

  const userName = user?.name;
  // no user name associated with phylotree/run means it was autogenerated
  const isAutoGenerated = Boolean(!userName);
  const displayName = isAutoGenerated ? "Weekly Auto-Build" : userName;

  const AUTOGENERATED_TREE_TEXT = (
    <div>This tree is automatically built by CZ GEN EPI every Monday</div>
  );

  return (
    <>
      <NextstrainConfirmationModal
        open={open}
        onClose={handleClose}
        treeId={treeId}
      />
      <StyledRowContent
        className={dataTableStyle.cell}
        onClick={handleClickOpen}
        disabled={isDisabled}
      >
        <CellWrapper data-test-id="tree-name-cell">
          <TreeIcon className={dataTableStyle.icon} />
          <StyledNameWrapper>
            <span>
              {value} <PhyloTreeStatusTag treeStatus={status} />
            </span>
            <StyledTreeCreator>
              {displayName}
              {isAutoGenerated && (
                <StyledTooltip
                  arrow
                  leaveDelay={200}
                  title={AUTOGENERATED_TREE_TEXT}
                  placement="bottom"
                >
                  <StyledInfoOutlinedIcon />
                </StyledTooltip>
              )}
            </StyledTreeCreator>
          </StyledNameWrapper>
        </CellWrapper>
      </StyledRowContent>
    </>
  );
};

export default TreeTableNameCell;
