name: Clean up stale happy stacks every hour

on:
  schedule:
    # Runs "every 55th minute" (see https://crontab.guru)
    - cron: "55 * * * *"

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Clean happy stacks
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: HappyCleanupGenepiRdevStacks
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1800
      - name: Clean up stale happy stacks
        uses: chanzuckerberg/github-actions/.github/actions/happy-cleanup@happy-cleanup-v1.1.5
        with:
          tfe_token: ${{secrets.TFE_TOKEN}}
          # the default stale period to delete a stack is 2 weeks
          # override like this:
          time: 5 days
