name: Scheduled Deploy

on:
  schedule:
    # Weekly Tuesday & Thursdays @ 16:00 UTC (8am PST [winter] / 9am PDT [summer])
     - cron: '0 16 * * 2,4'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to use for a deploy (defaults to latest successful staging deploy)'
        required: false
        default: ''
      environment:
        description: 'deploy to staging or prod'
        required: false
        default: 'prod'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_REPO: ${{ secrets.ECR_REPO }}/
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upgrade:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Prod Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_PROD_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
      - uses: actions/checkout@v2
      - name: Determine the tag
        uses: chanzuckerberg/github-actions/.github/actions/latest-successful-deployment@latest-successful-deployment-v1.0.1
        with:
          environment: staging
          owner: chanzuckerberg
          repo: czgenepi
          happy_version: "0.41.0"
      - name: Generate payload
        run: |
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
              echo "Using workflow dispatch to deploy tag ${{ github.event.inputs.image_tag }}"
              echo "payload={\"tag\":\"${{ github.event.inputs.image_tag }}\"}" >> $GITHUB_ENV
          else
              echo "payload={\"tag\":\"sha-${DEPLOY_SHA:0:8}\"}" >> $GITHUB_ENV
          fi
      - uses: avakar/create-deployment@v1.0.2
        with:
          auto_merge: false
          environment: ${{ github.event.inputs.environment || 'prod' }}
          payload: ${{ env.payload }}
          required_contexts: ""
        env:
          GITHUB_TOKEN: ${{ secrets.CZIBUILDBOT_GITHUB_TOKEN }}
