name: Scheduled Prod Deploy Test

on:
  push:
    branches:
      - lvreynoso/scheduled_prod_deploy

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_REPO: ${{ secrets.ECR_REPO }}/
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upgrade:
    runs-on: ubuntu-20.04
    environment:
      name: staging
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        if: always()
      - name: Configure AWS RDEV Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
      - uses: actions/checkout@v2
      - name: Install happy dependencies
        run: |
          pip install -r .happy/requirements.txt
      - name: Update deployment
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        run: |
          export DEPLOY_SHA=sha-$(python3 ./scripts/happy-deploy.py staging --get-latest)
          ./scripts/happy --profile="" --env rdev update lvr-deploy-test --tag $DEPLOY_SHA
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
